package actions

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/cyberark/idsec-sdk-golang/pkg/auth"
	"github.com/cyberark/idsec-sdk-golang/pkg/profiles"
	k8sservice "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/k8s"
	k8smodels "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/k8s/models"
)

// IdsecKubectlLoginAction wires the kubectl exec credential plugin logic into the
// command tree in two places:
//
//  1. `idsec exec sca k8s elevate` — the canonical command. Its flags are already
//     generated by the schema framework from IdsecSCAK8sElevateKubectlRequest; this
//     action only overrides the Run function so that raw ExecCredential JSON is
//     written directly to os.Stdout instead of going through args.PrintSuccess
//     (which would add ANSI colours that break kubectl's JSON parser).
//
//  2. `idsec kubectl-login` — a hidden root-level alias for the same behaviour,
//     kept for kubeconfig brevity. The alias defines its own flags via addElevateFlags
//     so it works without the exec parent hierarchy.
//
// Both entry points share the same runKubectlLoginAction function body.
//
// AWS kubeconfig example (--fqdn is always the cluster identifier):
//
//	args:
//	  - "kubectl-login"
//	  - "--csp"
//	  - "AWS"
//	  - "--role-id"
//	  - "arn:aws:iam::134672441550:role/k8s_sca_test_role"
//	  - "--fqdn"
//	  - "745445889F087548523CF96B3D365FF0.gr7.us-east-1.eks.amazonaws.com"
type IdsecKubectlLoginAction struct {
	profilesLoader *profiles.ProfileLoader
}

// NewIdsecKubectlLoginAction creates a new IdsecKubectlLoginAction.
func NewIdsecKubectlLoginAction(profilesLoader *profiles.ProfileLoader) *IdsecKubectlLoginAction {
	return &IdsecKubectlLoginAction{
		profilesLoader: profilesLoader,
	}
}

// DefineAction must be called AFTER NewIdsecServiceExecAction.DefineAction so that
// the exec → sca → k8s → elevate cobra subtree already exists when we walk it.
func (a *IdsecKubectlLoginAction) DefineAction(cmd *cobra.Command) {
	// ── 1. Override exec sca k8s elevate ────────────────────────────────────
	// The schema framework (IdsecServiceExecAction) has already created the
	// elevate subcommand with the correct flags from IdsecSCAK8sElevateKubectlRequest.
	// We only replace Run so that ExecCredential JSON goes to os.Stdout directly.
	if elevateCmd := findNestedCommand(cmd, "exec", "sca", "k8s", "elevate"); elevateCmd != nil {
		elevateCmd.SilenceUsage = true
		elevateCmd.Run = a.runKubectlLoginAction
	}

	// ── 2. Hidden root-level kubectl-login alias ─────────────────────────────
	// Hidden keeps it out of `idsec --help` while still being reachable by
	// kubectl exec plugin invocations that use the short-form kubeconfig.
	aliasCmd := &cobra.Command{
		Use:          "kubectl-login",
		Short:        "Alias for 'sca k8s elevate' — kubectl Exec Credential Plugin",
		Hidden:       true,
		SilenceUsage: true,
		Run:          a.runKubectlLoginAction,
	}
	addElevateFlags(aliasCmd)
	cmd.AddCommand(aliasCmd)
}

// addElevateFlags registers the kubectl exec plugin flags on cmd.
// Called for the hidden root alias; exec sca k8s elevate gets these flags
// from the IdsecSCAK8sElevateKubectlRequest schema instead.
func addElevateFlags(c *cobra.Command) {
	c.Flags().String("profile-name", profiles.DefaultProfileName(), "idsec profile to load for ISP authentication")
	c.Flags().String("csp", "", "Cloud provider: AWS or AZURE (required)")
	c.Flags().String("role-id", "", "IAM role ARN (AWS); provide either --role-id or --role-name")
	c.Flags().String("role-name", "", "IAM role name; provide either --role-id or --role-name")
	c.Flags().String("fqdn", "", "Cluster API endpoint FQDN — always used in kubeconfig (e.g. xxxx.gr7.us-east-1.eks.amazonaws.com)")
	c.Flags().String("target-id", "", "EKS cluster ARN; alternative to --fqdn when used with --workspace-id")
	c.Flags().String("workspace-id", "", "AWS account ID / Azure subscription ID (optional when --fqdn is provided)")
	c.Flags().String("tenant-id", "", "Azure Entra tenant ID (future Azure AKS support)")
}

// findNestedCommand walks a cobra command tree by successive name segments and
// returns the deepest matching command, or nil if any segment is not found.
func findNestedCommand(root *cobra.Command, names ...string) *cobra.Command {
	cur := root
	for _, name := range names {
		var next *cobra.Command
		for _, sub := range cur.Commands() {
			if sub.Name() == name {
				next = sub
				break
			}
		}
		if next == nil {
			return nil
		}
		cur = next
	}
	return cur
}

// runKubectlLoginAction executes the full kubectl-login flow.
// All errors are written to os.Stderr and the process exits with code 1.
// On success, only the ExecCredential JSON is written to os.Stdout.
func (a *IdsecKubectlLoginAction) runKubectlLoginAction(cmd *cobra.Command, _ []string) {
	// --- 1. Parse flags ---
	profileName, _ := cmd.Flags().GetString("profile-name")
	csp, _ := cmd.Flags().GetString("csp")
	roleID, _ := cmd.Flags().GetString("role-id")
	roleName, _ := cmd.Flags().GetString("role-name")
	fqdn, _ := cmd.Flags().GetString("fqdn")
	targetID, _ := cmd.Flags().GetString("target-id")
	workspaceID, _ := cmd.Flags().GetString("workspace-id")
	tenantID, _ := cmd.Flags().GetString("tenant-id")

	// --- 2. Validate required flags ---
	cspUpper := strings.ToUpper(strings.TrimSpace(csp))
	if cspUpper == "" {
		exitErr("--csp is required (e.g. AWS or AZURE)")
	}
	if strings.TrimSpace(roleID) == "" && strings.TrimSpace(roleName) == "" {
		exitErr("one of --role-id or --role-name is required")
	}

	// Cluster must be identified by FQDN alone OR by (WorkspaceID + TargetID).
	fqdnClean := strings.TrimSpace(fqdn)
	targetIDClean := strings.TrimSpace(targetID)
	workspaceIDClean := strings.TrimSpace(workspaceID)

	hasFQDN := fqdnClean != ""
	hasWorkspaceAndTarget := workspaceIDClean != "" && targetIDClean != ""
	if !hasFQDN && !hasWorkspaceAndTarget {
		exitErr("--fqdn is required (or provide both --workspace-id and --target-id)")
	}

	// --- 3. Load idsec profile ---
	profile, err := (*a.profilesLoader).LoadProfile(profiles.DeduceProfileName(profileName))
	if err != nil || profile == nil {
		exitErr("no idsec profile found — run 'idsec login' first to authenticate")
	}

	// --- 4. Load ISP authentication from keyring (no interactive prompt) ---
	ispAuthenticator, ok := auth.SupportedAuthenticators["isp"]
	if !ok {
		exitErr("ISP authenticator is not available in this build")
	}

	if _, hasISP := profile.AuthProfiles["isp"]; !hasISP {
		exitErr(fmt.Sprintf("profile '%s' has no ISP auth configured — run 'idsec login' first", profile.ProfileName))
	}

	// LoadAuthentication loads the cached token into the authenticator's internal state.
	loadedToken, err := ispAuthenticator.LoadAuthentication(profile, true)
	if err != nil || loadedToken == nil {
		exitErr("idsec session expired or not found — run 'idsec login' to re-authenticate")
	}

	// --- 5. Determine cache key component (always fqdn when available) ---
	roleKey := roleID
	if roleKey == "" {
		roleKey = roleName
	}
	// fqdn is always provided when kubeconfig uses --fqdn; use it for the cache key.
	// If using --target-id path, fall back to targetID as the unique cluster identifier.
	cacheIdentifier := fqdnClean
	if cacheIdentifier == "" {
		cacheIdentifier = targetIDClean
	}

	// --- 6. Get CSP-specific token provider ---
	provider, err := k8sservice.GetTokenProvider(cspUpper)
	if err != nil {
		exitErr(fmt.Sprintf("unsupported CSP %q: %v", cspUpper, err))
	}

	// --- 7. Check keyring cache using per-CSP TTL ---
	var elevateResult *k8smodels.IdsecSCAK8sElevateResult

	cached, err := LoadCachedCreds(cspUpper, roleKey, cacheIdentifier, provider.ElevateTTL())
	if err != nil {
		// Non-fatal: cache read failure — fall through to Elevate API call.
		fmt.Fprintf(os.Stderr, "warning: failed to read cached credentials: %v\n", err)
	}

	if cached != nil {
		elevateResult = cached
	} else {
		// --- 8. Cache miss or expired — call the SCA Elevate API ---
		svc, err := k8sservice.NewIdsecSCAK8sService(ispAuthenticator)
		if err != nil {
			exitErr(fmt.Sprintf("failed to initialize SCA K8s service: %v", err))
		}

		elevateResp, err := svc.Elevate(&k8smodels.IdsecSCAK8sElevateKubectlRequest{
			CSP:         cspUpper,
			RoleID:      roleID,
			RoleName:    roleName,
			FQDN:        fqdnClean,
			TargetID:    targetIDClean,
			WorkspaceID: workspaceIDClean,
			TenantID:    tenantID,
		})
		if err != nil {
			exitErr(fmt.Sprintf("elevate API call failed: %v", err))
		}
		if len(elevateResp.Response.Results) == 0 {
			exitErr("elevate API returned no results for the requested cluster/role")
		}

		elevateResult = &elevateResp.Response.Results[0]

		// Persist to keyring — non-fatal if it fails; next call will re-elevate.
		if saveErr := SaveCreds(cspUpper, roleKey, cacheIdentifier, elevateResult); saveErr != nil {
			fmt.Fprintf(os.Stderr, "warning: failed to cache elevated credentials: %v\n", saveErr)
		}
	}

	// --- 9. Build cluster context ---
	// For AWS, parse region and cluster name from the targetId returned in the
	// elevate response (e.g. "arn:aws:eks:us-east-1:123456:cluster/my-cluster").
	// These are no longer provided as CLI flags.
	clusterCtx := &k8sservice.IdsecSCAK8sClusterContext{
		CSP:         cspUpper,
		WorkspaceID: workspaceIDClean,
		TenantID:    tenantID,
		RoleID:      roleID,
		RoleName:    roleName,
		FQDN:        fqdnClean,
	}

	if cspUpper == "AWS" && elevateResult.TargetID != "" {
		region, clusterName, parseErr := k8sservice.ParseEKSARN(elevateResult.TargetID)
		if parseErr != nil {
			exitErr(fmt.Sprintf("failed to parse EKS ARN from elevate response targetId %q: %v", elevateResult.TargetID, parseErr))
		}
		clusterCtx.Region = region
		clusterCtx.ClusterID = clusterName
	}

	// --- 10. Generate the kubectl token (EKS presigned URL for AWS) ---
	execCred, err := provider.GenerateToken(elevateResult, clusterCtx)
	if err != nil {
		exitErr(fmt.Sprintf("failed to generate %s token: %v", cspUpper, err))
	}

	// --- 11. Write ExecCredential JSON to stdout ONLY ---
	if err := json.NewEncoder(os.Stdout).Encode(execCred); err != nil {
		exitErr(fmt.Sprintf("failed to encode ExecCredential: %v", err))
	}
}

// exitErr writes msg to stderr and exits with code 1.
// This is the only way this command terminates on failure so kubectl
// always sees a clean, parseable stdout.
func exitErr(msg string) {
	fmt.Fprintf(os.Stderr, "idsec kubectl-login: %s\n", msg)
	os.Exit(1)
}
